version: '3'
services:
  master:
    build:
        context: .
        args:
          install_path: /usr/local
    container_name: elastic-master
    user: elasticsearch
    environment:
      - discovery.type=single-node
      - "PAGENT_PATH=-agentpath:/usr/local/jprofiler11.1.2/bin/linux-x64/libjprofilerti.so=port=8849,nowait"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticmasterdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
      - 8849:8849
    networks:
      - elasticnet
  slave:
    build:
        context: .
        args:
          install_path: /usr/local
    user: elasticsearch
    environment:
      - discovery.type=single-node
      - "PAGENT_PATH=-agentpath:/usr/local/jprofiler11.1.2/bin/linux-x64/libjprofilerti.so=port=8849,nowait"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticslavedata:/usr/share/elasticsearch/data
    ports:
      - 8849
    networks:
      - elasticnet

volumes:
  elasticmasterdata:
    driver: local
  elasticslavedata:
    driver: local

networks:
  elasticnet:
    driver: bridge