version: '3'
services:
  elasticsearch:
    build:
        context: .
        args:
          install_path: /usr/local
    container_name: elasticsearch
    user: elasticsearch
    environment:
      - discovery.type=single-node
      - "PAGENT_PATH=-agentpath:/usr/local/jprofiler11.1.2/bin/linux-x64/libjprofilerti.so=port=8849,nowait"
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
      - 8849:8849
    networks:
      - elasticnet

volumes:
  elasticdata:
    driver: local
    
networks:
  elasticnet:
    driver: bridge